name: Dummy Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, world!"
      - name: azure login
        run: az login --service-principal --username ee5c28cb-b1b2-4ecf-9745-82a94d92b58c --password Ukv8Q~dP5CNCpb3.5H_GXQx68FuBV~We6agQIalf --tenant 251e8d5a-0557-476d-8f02-7b08a04f861e

  
