name: Dummy Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, world!"
      - name: azure login
        run: az login --service-principal --username 5155679f-5b82-4589-8521-6c6c2a50a73c --password _e68Q~wnwEcMu0Hq66e21CvV2BAHuuljzoCW0aAm --tenant 44ff9492-6357-4790-9759-8d5b4666c643



        # INSTALL TERRAFORM
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      
      - name: Terraform Init
        run: terraform init

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6.3.0
        with:
          tflint_version: latest
           
      # 5. Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # 6. Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
